name: Build
on:
  - push
  - pull_request

jobs:
  build:
    name: Ruby ${{ matrix.ruby }} / Rails ${{ matrix.rails }}
    strategy:
      fail-fast: false
      matrix:
        ruby: ['3.3', '3.2', '3.1']
        rails: ['7.0', '7.1']

    runs-on: 'ubuntu-latest'
    env:
      ARUBA_TIMEOUT: 240
      BUNDLE_GEMFILE: gemfiles/rails${{ matrix.rails }}.gemfile

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'yarn'
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
      - name: Setup project
        run: |
          npm install -g yarn
          yarn install
          bundle install
      - name: Run test
        run: bundle exec rspec
